
# ------------------------------------------
# PROBLEM 2
# ------------------------------------------

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# ------------------------------------------
# PSEUDO-CODE
# ------------------------------------------

# set fib3 to equal fib1 + fib2
# check if fib3 is divisible by 2
# push fib2 down the line, making it the new fib1
# push fib3 down the line, making it the new fib2

# ------------------------------------------
# SOLUTION
# ------------------------------------------

fib1 = 1
fib2 = 2

# start counter at 2 so I dont have to account for fib2 in my if statement

counter = 2

while fib1 < 4000000
  fib3 = fib1 + fib2 
  if fib3%2 == 0
    counter += fib3
  end
  fib1 = fib2
  fib2 = fib3
end

p counter

# 1 + 2 = 3
# 2 + 3 = 5
